BS-558: Added Underpayments feature flag
hmrc/breathing-space-if-proxy pull request #133
Opened 2022-02-03 12:17 UTC by tgeary90

2022-02-03 12:17 UTC, tgeary90 commented
`2022-02-03 12:14:27,777 level=[INFO] logger=[uk.gov.hmrc.breathingspaceifproxy.controller.UnderpaymentsController] thread=[application-akka.actor.default-dispatcher-6] rid=[] user=[] message=[Underpayments feature enabled : true] `

2022-02-04 11:33 UTC, macgrewal requested changes
The `.conf` files in the test resources can be removed and config can be overridden in the tests

2022-02-04 11:33 UTC, macgrewal commented on test/uk/gov/hmrc/breathingspaceifproxy/controller/UnderpaymentsControllerSpec.scala
> +      val flaggedOnAppConfig = new AppConfig(flaggedOffConfig, servicesConfig)
```suggestion
      val featureConfig = Configuration.from(Map("feature.flag.underpayments.enabled" -> true))
      val flaggedOnConfig = featureConfig.withFallback(inject[Configuration])
      val servicesConfig = inject[ServicesConfig]
      val flaggedOnAppConfig = new AppConfig(flaggedOnConfig, servicesConfig)
```

2022-02-04 11:33 UTC, macgrewal commented on test/uk/gov/hmrc/breathingspaceifproxy/controller/UnderpaymentsControllerSpec.scala
> +      val flaggedOffAppConfig = new AppConfig(flaggedOffConfig, servicesConfig)
```suggestion
      val featureConfig = Configuration.from(Map("feature.flag.underpayments.enabled" -> false))
      val flaggedOffConfig = featureConfig.withFallback(inject[Configuration])
      val servicesConfig = inject[ServicesConfig]
      val flaggedOffAppConfig = new AppConfig(flaggedOffConfig, servicesConfig)
```

2022-02-04 13:18 UTC, tgeary90 commented on test/uk/gov/hmrc/breathingspaceifproxy/controller/UnderpaymentsControllerSpec.scala
> +      val flaggedOnAppConfig = new AppConfig(flaggedOffConfig, servicesConfig)
done

2022-02-04 14:08 UTC, macgrewal approved these changes

2022-02-04 14:08 UTC, merged